### ISSUE TITLE
console error on map loop in recipe.jsx

### ISSUE THREAD

**Issue by nadav-galili** [nadav-galili/React-recipe-app#1]

**Comment by tonytangdev** [comment]
Hi !

I fixed your code here #2  ! :)

You were passing an object in the key prop.

```
{ingredients.map((ingredient) => (
    <li key={ingredient}>{ingredient.text}</li>
))}
```

So I added the index parameter in the map function to try to have a unique key.
And instead of passing the object `ingredient` to key, I pass in `${ingredient.text}-${index}`.

```
{ingredients.map((ingredient, index) => (
    // The key must be an unique string among your ingredients
    <li key={`${ingredient.text}-${index}`}>{ingredient.text}</li>
))}
```

That way, your application is more optimized for react to render.

To learn more about list and keys in react : [https://reactjs.org/docs/lists-and-keys.html#keys](https://reactjs.org/docs/lists-and-keys.html#keys)
